language: go
go: 1.9.x

services:
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

before_script:
  - psql -U postgres -c "create extension postgis"
  - cd gsky/mas/gdb && psql -f schema.sql -U postgres

install: true

script:
  - go tool vet .
